/**
 * Arvyon dApp constants.
 *
 * Contract addresses and the active network are read dynamically from
 * src/contracts/deployments.json, which is generated by the contracts deploy
 * pipeline (`node contracts/scripts/sync-config.js`). Nothing is hardcoded;
 * redeploying and re-syncing updates the dApp automatically. Per-value
 * NEXT_PUBLIC_* env vars still override when set.
 */
import abi from "@/src/contracts/abi.json";
import deployments from "@/src/contracts/deployments.json";

const EXPLORERS: Record<number, string> = {
  11155111: "https://sepolia.etherscan.io",
  1: "https://etherscan.io",
  31337: "http://localhost:8545",
};

const CHAIN_NAMES: Record<number, string> = {
  11155111: "Sepolia",
  1: "Ethereum",
  31337: "Localhost",
};

export const CHAIN_ID = deployments.chainId;
export const CHAIN_ID_HEX = "0x" + CHAIN_ID.toString(16);

export const NETWORK = {
  chainId: CHAIN_ID,
  chainIdHex: CHAIN_ID_HEX,
  name: CHAIN_NAMES[CHAIN_ID] || deployments.network || "Unknown",
  rpcUrl:
    process.env.NEXT_PUBLIC_RPC_URL || "https://ethereum-sepolia-rpc.publicnode.com",
  explorer: EXPLORERS[CHAIN_ID] || "https://sepolia.etherscan.io",
  nativeCurrency: { name: "Ether", symbol: "ETH", decimals: 18 },
};

export const CONTRACTS = {
  PolicyRegistry:
    process.env.NEXT_PUBLIC_POLICY_REGISTRY || deployments.contracts.PolicyRegistry,
  PDRLogger:
    process.env.NEXT_PUBLIC_PDR_LOGGER || deployments.contracts.PDRLogger,
  Executor: process.env.NEXT_PUBLIC_EXECUTOR || deployments.contracts.Executor,
} as const;

export const ABIS = abi as {
  PolicyRegistry: object[];
  PDRLogger: object[];
  Executor: object[];
};

export type ContractName = keyof typeof CONTRACTS;

export function explorerAddress(address: string): string {
  return `${NETWORK.explorer}/address/${address}`;
}

export function explorerTx(hash: string): string {
  return `${NETWORK.explorer}/tx/${hash}`;
}
